name: medical_xai
channels:
  - conda-forge
  - apple
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.7.5
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - opencv=4.8.1
  - jupyter
  - pillow=10.3.0
  - tqdm
  - pip:
    - tensorflow-macos==2.16.2
    - tensorflow-metal==1.1.0
    - streamlit==1.36.0
    - albumentations==1.4.16